server:
  port:9090
spring:
  cloud:
    gateway:
      routes:
        - id: hospital_management_service
          uri: 'http://localhost:8080'
          predicates:
            - Path=/hospital/**
        - id: urgency_management_service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/urgency/**